### ISSUE TITLE
Treatment of contributor names

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1042]
**Child Issues:**

* #1344

## Description

Presently, where a GitHub ID is provided in an article's contributors field, the front-end *replaces* the contributor's name as written in the contributors field with the GH profile name for that GH ID.  Likewise, the Contributors page uses the GH profiles as the authoritative name for each contributor.   

We do have a mechanism to override the GH profile name and also manage alphabetization problems on a case by case basis.  However this requires us to periodically review the Contributors page for problems because people can change their profile names at will.

While I understand that the Contributors page needs to define some authoritative name because the names provided in the individual articles might be be completely consistent (e.g., "David Bernholdt" vs "David E. Bernholdt" vs "D.E. Bernholdt" vs...), I feel that the substitution of the provided name in an individual article with the one from the GH profile may yield unexpected and undesirable results.

Two examples are Elsa, who's profile name is "Elsa Gonsiorowski, PhD" and Mark, who recently changed his profile to "Mark (he/him) C. Miller".  In my opinion, both of these look out of place in the individual articles when the front-end substitutes them in.  Personally, I'm less concerned about them appearing that way in the Contributors page.

So we can use the new name mapping capability (specified using the Site/Contributors.md file) to replace the GH profile name with one of our choosing *everywhere* on the site.  But, as noted above, we have to actually detect and respond to such situations.

I propose a new default:
1) The front-end should use the name provided in the contributors field rather than replacing it with the GH profile name
2) The Contributors page is fine built with GH profile names, and we have the option to override those as needed using the Contributors.md mechanism.

To see this in real life, look at the contributor pages and follow a few of the links to their articles:
* https://bssw.io/items?author=gonsiorowski
* https://bssw.io/items?author=miller

## Tasks
- [x] ask PC to use the names provided in the `Contributed by` field in all articles instead of replacing them with GH profile names
- [x] ask SBX/PC to change the Contributors page and individual contributor pages as we discussed
- [ ] add checking of contributor profile information to the PR checklist
- [ ] develop some short, simple standard language to convey out intent/request to authors
- [ ] work with key team members to ensure appropriate communications with authors
  - [ ] Blogs (Lois and David)
  - [ ] HPC-BP webinars (Osni)
  - [ ] SWR panels (Elaine)
- [ ] we need to establish a practice of regular review of the Contributors page cases where we might want to locally override the GH profile name.  Is monthly enough?

**Comment by bernhold** [comment]
@markcmiller86 as one of the people directly affected by this, I'd particularly appreciate your input.  What do you think is expected/reasonable on the site?  Thanks

**Comment by bernhold** [comment]
P.S.  I'm hoping that we can have a short discussion of this issue at our next operational meeting, reach a consensus, and move on quickly.  This should not be a drawn-out discussion.

**Comment by bartlettroscoe** [comment]
@bernhold, I agree with your assessment and I am good with your proposed fix (and I am surprised that it is being replaced).

**Comment by bernhold** [comment]
The consensus of the EB discussion on 2021-09-09 was that:
1) For articles, the name provided in the `Contributed by` heading should be used in the rendering, even if the name is linked to a GH profile. The current behavior is to *replace* the provided name with the GH profile name.  This too often leads to undesirable results.
2) On the Contributors page, it is reasonable to use the GH profile name and there is a mechanism to override that (controlled by Site/Contributors.md) on an individual basis.

@markcmiller86 since you were not able to attend today's EB meeting, and you're an example of the situation we're trying to address, I'd appreciate if you can confirm this approach "works" for you?  Thanks

**Comment by bernhold** [comment]
Notified PC of our decision via Basecamp.  They will have to implement (1) above. (2) is existing behavior.

**Comment by bernhold** [comment]
Consensus of 2021-09-23 EB discussion...

* We agreed that on the [Contributors](https://bssw.io/items/authors) page, we can remove the GitHub link, the affiliation, and the number of contributions info (saving space) and put this info on the individual contributor pages (e.g., <https://bssw.io/items?author=rouson>)
* Images on Contributors page, in addition to contributor name, should be linked to individual contributor pages
* We believe that if people are comfortable with their GH profile (name, image, affiliation), they're probably okay with that same information appearing on the BSSw Contributors page...
* ... However this may be an unexpected use of their GH profile content, so...
* ... We should be consistent in letting contributors know that we're using their GH profile info in this way
  - Currently, most new contributors come in through (a) blog postings, (b) HPC-BP webinar events, and (c) SWR panel events.  We need to work with the people handling these to ensure that the appropriate communications take place.
* And we should periodically review the Contributors page for content that might be more questionable (recalling that people can change their GH profile content at any time) and reach out to see if they want something different in their "BSSw profile". (We can do this using the mapping capabilities through the Site/Contributors.md file.)

**Comment by bernhold** [comment]
Action items:
- [ ] notify SBX/PC of our desire to change the Contributors page
- [ ] add checking of contributor profile information to the PR checklist
- [ ] develop some short, simple standard language to convey out intent/request to authors
- [ ] work with key team members to ensure appropriate communications with authors
  - [ ] Blogs (Lois and David)
  - [ ] HPC-BP webinars (Osni)
  - [ ] SWR panels (Elaine)
- [ ] we need to establish a practice of regular review of the Contributors page cases where we might want to locally override the GH profile name.  Is monthly enough?

**Comment by bartlettroscoe** [comment]
@bernhold, IMHO, we should move the checklist of action items in the [prior comment](https://github.com/betterscientificsoftware/bssw.io/issues/1042#issuecomment-926116827) to a **Task** section in first comment so that it is easy to find.  Also, GitHub treats checklist items in that box specially.

**Comment by bernhold** [comment]
@bartlettroscoe done, unnecessary comment deleted to avoid confusion.

**Comment by bartlettroscoe** [comment]
Related to this, I just noticed that the author's name in an article on BSSw.io is linked to their GitHub account instead of to their contributor page on bssw.io.  For example, for the article:

* https://bssw.io/items/pull-request-size-matters

the author link at the top "MARK (HE/HIS) C. MILLER" shown in:

![image](https://user-images.githubusercontent.com/1959736/134712201-6edc2c40-e79e-4c01-b5a4-46f9bbf64552.png)

links to:

* https://bssw.io/items?author=miller

instead of:

* https://bssw.io/items?author=miller

I think it would be better for the author's name in the article to link to their bssw.io contributor page instead of their GitHub page.  Note there is a link to the author's GitHub page from their bssw.io contributor page as shown at:

* https://bssw.io/items?author=miller

showing:

![image](https://user-images.githubusercontent.com/1959736/134712409-d1fe4339-c64f-4f7e-b882-c5119505fadb.png)

**Comment by bernhold** [comment]
That's a good point.  I agree. That may already be on the list of pending changes, but I'll add it to make sure.

**Comment by bernhold** [comment]
Actually, @bartlettroscoe I didn't read and check carefully enough.  Mark's name in the article links to his BSSw author page.  Not directly to his GH profile.  I think that's the behavior you're asking for. And after your first sentence, everything seems consistent with that, both as current state and as desired state.  Am I missing something?

**Comment by bartlettroscoe** [comment]
>  Mark's name in the article links to his BSSw author page.

@bernhold, that is strange.  I just checked and now it does link to the bssw.io author page.  I swear it was linking to the GitHub page.

**Comment by rinkug** [comment]
This seems to work fine now. from what I see.

**Comment by bartlettroscoe** [comment]
NOTE: @bernhold explained what the current handling is in https://github.com/betterscientificsoftware/bssw.io/issues/1344#issuecomment-1137902067.

**Comment by rinkug** [comment]
@bernhold to check if this can be closed.
