### ISSUE TITLE
Category/topic for RSEs?

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1552]
We don't really have a topic for articles that focus on RSEs.  Maybe not even a good category.

Maybe it could be as simple as something like "Research Software Engineering" under Better Collaboration?  (Or maybe "Research Software Engineers" depending on whether we want to emphasize process or people.) But maybe Better Collaboration isn't even the right category.

Are there other people-related or career-track related or other topics we might also want to add?

**Comment by rinkug** [comment]
Based on discussion today: We have many titles across the spectrum of labs, academia and industry.  So, do we need to focus on RSEs.

From the other standpoint, we have around 60+ hits on RSE. So, maybe highlighting it in diff category is worthwhile.

Where does it fit in our current categories? Maybe "better skills" is the right category? Do we need a new category?
Possible topic names?
* career development?
* career paths?
* RSE career paths?

We could not reach a consensus where this fits in right now:

Action item: Search "RSE" and decide how many fit in a new bin related to RSEs?  Also, look at "careers" in general.
Mark and Pat will contribute to this effort.

**Comment by markcmiller86** [comment]
So, we have a bunch of *already published* content out there that have text matches that might fit under this new heading/label. To understand how this new heading/lable would work, we'd want to take a look at those articles. But, we should take care when undertaking this because which content that is depends on how we decide to search...

- `"research software engineeer"` returns [ these 67 articles](https://bssw.io/items/search?search_string=%22research+software+engineer%22)
- `"RSE"` returns [these 64 articles](https://bssw.io/items/search?search_string=%22RSE%22) several of which match on on the middle `rse` in `yourself`
- `" RSE"` returns [this 1 article](https://bssw.io/items/search?search_string=%22+RSE%22) that has `RSE` in the article's title
- `"RSE "` returns [these 56 articles](https://bssw.io/items/search?search_string=%22RSE+%22) that have `RSE` in the body.
- `"research software engineer" OR "RSE" site:bssw.io` from Google returns [these 137 articles](https://www.google.com/search?q=%22research+software+engineer%22+OR+%22RSE%22+site%3Abssw.io&lr=&safe=active&hl=en&as_qdr=all&sxsrf=AJOqlzVs-XfNvQVk72DBR-FIVs4u-GEaxA%3A1678389090321&ei=Yi8KZNGaE7zPkPIP3u6mwAM&ved=0ahUKEwjR05fMxs_9AhW8J0QIHV63CTgQ4dUDCA8&uact=5&oq=%22research+software+engineer%22+OR+%22RSE%22+site%3Abssw.io&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQA0oECEEYAVD7BVjyG2DcH2gDcAB4AIABQYgB5QOSAQE4mAEAoAEBwAEB&sclient=gws-wiz-serp)
- `find . -name '*.md' -exec grep -q -w -i "research software engineer"\\\|"RSE" {} \; -print` from top of repo returns 59 articles

Setting aside the somewhat odd behavior of bssw.io search, to understand impact, we should agree on which articles to have a closer look at to decide if and how the new label will apply and work.

Taking the last search as gospel and filtering out stuff in `Events`, `Site` and `docs`, we have these...

- [ ] ./Articles/Blog/MakingOpenSourceResearchSwVisible.md
- [ ] ./Articles/Blog/SCSoftwareConference.md
- [ ] ./Articles/Blog/ResearchSoftwareEngineerANewCareerTrack.md
- [ ] ./Articles/Blog/2022-12-MutualOwnershipInRSE.md
- [ ] ./Articles/Blog/2020-01-usrse.md
- [ ] ./Articles/Blog/2023-02-anatomy-rse-team.md
- [ ] ./Articles/Blog/BSSwFellowsAnnouncement2019.md
- [ ] ./Articles/Blog/2021-08-registry-best-practices.md
- [ ] ./Articles/Blog/BSSwHighlights2020.md
- [ ] ./Articles/Blog/RSE-HPC-2020Workshop.md
- [ ] ./Articles/Blog/BSSwHighlights2021.md
- [ ] ./Articles/Blog/2022-10-reading-list.md
- [ ] ./Articles/Blog/2022-04-wosss-workshop-series.md
- [ ] ./Articles/Blog/RseStoriesPodcast.md
- [ ] ./Articles/Blog/2021-12-sc21-swe-cse-bof.md
- [ ] ./Articles/Blog/BSSwHighlights2022.md
- [ ] ./Articles/Blog/2022-08-Team-of-Teams-Panel.md
- [ ] ./Articles/Blog/2020-03-software-communities.md
- [ ] ./Articles/Blog/2022-03-sc21-rse-workshop.md
- [ ] ./Articles/Blog/2022-01-2022BSSwFellowshipAnnounce.md
- [ ] ./Articles/Blog/2022-07-vive-la-difference-rse.md
- [ ] ./Articles/Blog/2022-07-BSSwFellows2021.md
- [ ] ./Articles/Blog/DataDrivenSustainability.md
- [ ] ./Articles/Blog/2020-02-ideas-report.md
- [ ] ./Articles/Blog/BSSwHighlights2018.md
- [ ] ./Articles/Blog/2021-03-siam-cse21-retrospective.md
- [ ] ./Articles/Blog/2021-09-CollegevilleReportDay1.md
- [ ] ./CuratedContent/BloggersWorthFollowing.md
- [ ] ./CuratedContent/AgileProjectManagement.md
- [ ] ./CuratedContent/SwProductivityAndSustainabilityForCseAndDataScience.SIAM-CSE17.md
- [ ] ./CuratedContent/NationalRSEOrgs.md
- [ ] ./CuratedContent/Intersect-training.md

**Comment by rinkug** [comment]
Related to #479

**Comment by rinkug** [comment]
Perhaps the topic could be called "Research Software Engineering (RSEng)". This would perhaps eliminate concerns of RSE, a type of profession, being listed as a topic.

**Comment by bernhold** [comment]
What would distinguish RSEng from the existing Software Engineering topic?

**Comment by rinkug** [comment]
> What would distinguish RSEng from the existing Software Engineering topic?

Perhaps we should label software engineering as research software engineering? To me, they are equivalent but that a different topic. 

But your comment did make me think that perhaps RSE (people) related resources cannot fit in there.

**Comment by rinkug** [comment]
As per discussion, better collaboration is the category for this?

RSE is a community within our space, we have content but no topic to organize them.
Mark: whether we have RSE or not - its still ambiguous
David: We could list **Research Software Engineer(ing)** as a topic?  Reasoning: different people are referring to RSE ecosystem with Research Software Engineers  and Research Software Engineering terms. So, we address both with this term. 
Mark, Pat: do not like then parentheses and prefer Research Software Engineers.
Rinku: Neutral

ACTION:

Decision: We list Research Software Engineers under better collaboration. **@rinkug to do this.**

We need a what-is article to go with it **@rinkug will write this when she has time**.

We need to go through the above list that Mark created and add tags for this new topic. We wont look at past events (they are also not on above list). Future events will be categorized as needed under new topic. We do have two new events as of today that are RSE related. **@rinkug to do this.**

**Comment by rinkug** [comment]
> I think that the checked items in [#1552 (comment)](https://github.com/betterscientificsoftware/bssw.io/issues/1552#issuecomment-1462643557) should be tagged with the RSE topic. Also
> 
> * https://bssw.io/events/united-states-research-software-engineer-association-conference-2023-us-rse-23
> * https://bssw.io/events/research-software-engineers-in-escience-workshop-2023-sustainable-rse-ecosystems
> 
> Someone else might want to take an independent look at Mark's list to make sure I didn't miss anything significant.

Done.

**Comment by rinkug** [comment]
As per discussion, better collaboration is the category for this?

RSE is a community within our space, we have content but no topic to organize them.
Mark: whether we have RSE or not - its still ambiguous
David: We could list **Research Software Engineer(ing)** as a topic?  Reasoning: different people are referring to RSE ecosystem with Research Software Engineers  and Research Software Engineering terms. So, we address both with this term. 
Mark, Pat: do not like then parentheses and prefer Research Software Engineers.
Rinku: Neutral

ACTION:

- [x] We list "Research Software Engineers" as topic under better collaboration. Assigned to @rinkug . PR #1619 

- [x] Write a what-is article to go with it. Assigned to @rinkug . PR #1621 

- [x] We need to go through the above list that Mark created and add tags for this new topic. Assigned to @rinkug . PR #1620 

Note that we wont look at past events (they are also not on above list). Future events will be categorized as and when needed under this new topic. We do have two new events as of today that are RSE related (as mentioned by David in the below thread).

**Comment by rinkug** [comment]
> @bernhold : Do we want to consider tagging https://bssw.io/blog_posts/recap-encouraging-and-enabling-mutual-ownership-in-a-rse-community-of-practice

David replied "yes" to above.
