### ISSUE TITLE
Cleanup "WhatIs" files for all topics and updated EBdocs

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#1598]
Create/edit/delete "WhatIs" files for all topics and updated EBdocs as listed below

1. [x] Make list of all the WhatIs files for all categories and topics? Make a note of what is native, pdf or missing? (@rinkug )
2. [x] Assign folks to missing what-is files
3. [x] Assign folks to update pdf files
4. [x] Unpublish obsolete WhatIs files
5. [ ] Assign folks to review existing files for new content. Excel sheet can be found [HERE](https://docs.google.com/spreadsheets/d/1Bp7LHdhwnfncdp8l8o5QxkpWpG4i0gcK/edit#gid=1890549563).
6. [x] Remove "pinned:yes" from other non-WhatIs files (@rinkug PR #1599 ) 
7. [x] EB docs: Add all new topics (inclusivity, rse etc)  to EB docs (PR #1596)
9. [x] EB docs: Make section on how to create WhatIs files and why they are needed (PR #1596)
10. [ ] Decide: Where do WhatIs files fit in the github directory hierarchy?

Related to #560

**Comment by rinkug** [comment]
>  Is their title clean and meaningful?
We need to have something closer to topic but that makes a meaningful title for an article.
