### ISSUE TITLE
Add Keith Beattie  to bssw-editorial team

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#2000]
@betterscientificsoftware/bssw-editorial-board 

## Description

This issue is to track work to add Keith Beattie to the BSSw editorial team

## Tasks

* [x] Get Keith's GitHub ID ... @ksbeattie
* [x] Add Keith to BSSw.io repo GitHub teams
* [x] Editorial Mailing list
* [x] Google drive
* [x] Add Keith to bssw.io about/teams https://bssw.io/pages/team

**Comment by markcmiller86** [comment]
@ksbeattie FYI

**Comment by markcmiller86** [comment]
@betterscientificsoftware/bssw-editorial-board I could not find a way to invite @ksbeattie to the `@betterscientificsoftware/bssw-editorial-board` team. I looked on repo and in org and don't see a way to do that. Maybe only admin members can do it.

**Comment by bernhold** [comment]
Done

**Comment by bartlettroscoe** [comment]
@bernhold, what about

* https://github.com/orgs/betterscientificsoftware/teams/bssw-io-team

?

Are there any other on-boarding tasks (i.e. the ??? task above)?

**Comment by pagrubel** [comment]
What about adding him on bssw.io?
https://bssw.io/pages/team

**Comment by bernhold** [comment]
Suggestion: maybe someone can create an issue template for on-boarding a new EB member.
* Add to [bssw-editorial-board](https://github.com/orgs/betterscientificsoftware/teams/bssw-editorial-board) team
* Add to mailing list
* Add to https://bssw.io/pages/team

Anything else?

**Comment by markcmiller86** [comment]
I've added #2003
