### ISSUE TITLE
Transition BSSw.io GitHub Issue boards from Projects Classic to new Projects implementation before 8/32/2024

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#2107]
CC: @betterscientificsoftware/bssw-editorial-board 

## Description

It seems that GitHub support for the old Projects Classic Issue boards is ending.  For example, on 6/13/2024 the page:

* https://github.com/betterscientificsoftware/bssw.io/projects/3

is showing that support is ending "August 23, 2024" showing:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/8b1bec59-b82e-4f5e-8319-e342fd1670b4)

This issue is to track the transition from the old 

## Tasks

* [x] Transition the "BSSw Internal" board first and see what happens and what the issues are
* [x] Inform @betterscientificsoftware/bssw-editorial-board about this transition
* [x] Transition the "Content Development" board

**Comment by bernhold** [comment]
This is a dupe of #2060, but I can close that one.

The automatic migration has worked fine for me for other boards.  But any action that touches project boards will need to be revisited.  On the other hand, gh (the CLI) now has an extension for V2 projects, so it is not hard to write actions to manipulate the board.  I've done this for the HPC-BP webinar series to orchestrate the generation of a whole bunch of issues and adding them to the project board with all of the desired properties.

**Comment by bartlettroscoe** [comment]
As a first experiment, I will transition the TriBITS project boards:

* ??? 

When you click "Start Migration", you get the dialog:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/f89c3fbf-d760-43b1-aa3b-333261c14b9c)

NOTE: That suggests that automation will **NOT** be migrated.  Therefore, we will need to carefully note the automation before the migration and then manually set up the same automation.

**Comment by bartlettroscoe** [comment]
I just learned an interesting tidbit while transitioning the TriBITSPub/TriBITS projects.  If you want to maintain the project board IDs, you need to them in order.  I did not do that and I transitioned the classic project/2 first which become the new project/1 and then I transitioned the classic project/1 which become the new project/2.  In other words:

* "TriBITS": https://github.com/TriBITSPub/TriBITS/projects/2 => https://github.com/orgs/TriBITSPub/projects/1
* "TriBITS Refactor": https://github.com/TriBITSPub/TriBITS/projects/1 => https://github.com/orgs/TriBITSPub/projects/2

That is not the worst thing in world, the project "TriBITS" is meant to be the permeant project board while "TriBITS Refactor" was meant to be temporary during the big TriBITS refactor (which is basically done and therefore that board should likely go away).

But given that the existing classic boards are:

* "BSSw Internal": https://github.com/betterscientificsoftware/bssw.io/projects/2
* "Content Development": https://github.com/betterscientificsoftware/bssw.io/projects/3,

we would transition "BSSw Internal" first which will become the new board projects/1 and then transitioning "Content Development" next would make the new board projects/2.

So, I will go ahead and transition "BSSw Internal" first and carefully log my work and the checks.

**Comment by bartlettroscoe** [comment]
Before doing the migration of the "BSSw Internal" board, I will capture the existing structure and automations so we have something to compare against.

Where is what the board currently looks like:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/5d2fab22-209b-4f5f-a5f6-c8423d9000d7)

Here is the automation for the "Backlog" column:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/f944df52-70a6-4cde-8bdc-8041c8a8799d)

Here is the automation for the "Selected for development" column (there is none):

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/41268d8d-ad0b-40c7-9662-d4d75c449e1a)

Here is the automation for the "In progress" column:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/7ad3d7b4-2b81-4efb-b3b5-856d4979139f)

Here is the automation for the "Done" column:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/4364f265-6ec5-498a-a06c-8305851421d4)

These look like pretty standard automations but I will make sure they are maintained after the migration.

**Comment by bartlettroscoe** [comment]
I finished the initial transition of the board "BSSw Internal" and now it is at the page:

* https://github.com/orgs/betterscientificsoftware/projects/4/views/1

and it shows:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/68f7311a-8500-4ee4-9400-10938c35e7c3)

I also changed the name of the view from "View 1" to "Board" which shows up in the name of the tab.

Comparing to the screenshot before the transition [above](https://github.com/betterscientificsoftware/bssw.io/issues/2107#issuecomment-2176525210), one can see that the same number of issues are shown as well as the same ordering of issues at the top, the same note for the "Selected for development" column, etc.  Note that the issues are formatted differently with the new board not showing who created the issue.

The new project board shows both an expanded pop-up view for an issue issue like:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/a0fdde22-385a-4087-b04a-39a7304a7229)

and a compressed pop-up issue view for an issue (clicking the 📌icon) like:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/d81efbf8-962d-41a2-9629-e0ee0b4215ca)

Now for the automation.  I had to enable some of the automations.

For example, I enabled the "Item added to project" automation:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/f592413b-2e11-4404-b6e1-88d1054219d0)

This only adds new issues to the "Backlog" column.  There is no way to set up a different automation to set PRs to "In progress" like the old board.  (This is a feature regression w.r.t. the old board implementation.)

I then set the "item reopened" workflow step:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/d6a86074-2d28-4d1d-8f41-0dca81468a6a)

The "Item closed" automation was already set and enabled:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/d10d810b-0e0d-4de9-b09f-fcd2f4458607)

The "Pull request merged" automation was also already set:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/bcabf8bc-87fc-4eaf-a458-077e4439d829)

These new project automation functionality has very little flexibility.  With just a little bit of work, they could of allowed more than one automation for "Item added to project" or "Item reopened" to do different things for Issues vs. PRs.  Very disappointed :-(

**Comment by bartlettroscoe** [comment]
Now let me capture the setup for the existing "Content development" classic board:

*  https://github.com/orgs/betterscientificsoftware/projects/4/views/1

The project board currently looks like right now:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/5b0f76d3-8c5f-4efa-8769-a1476f0a4327)

Here is the "Idea Backlog" automation:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/0be14f14-30e0-4cad-8dec-1345e5f5894f)

There is no "Topic Review" automation.

There is no "Ready to write" automation.

There is no "In progress" automation.

Here is the "Item review" automation:

???

Here is the "Ready to publish" automation:

???

Here is the "Ready for digest" automation:

???

Here is the "Done" automation:

???

**Comment by bartlettroscoe** [comment]
@bernhold, @rinkug, @betterscientificsoftware/bssw-editorial-board,

I finished the migration of the "BSSw Internal" board:

* https://github.com/orgs/betterscientificsoftware/projects/4/views/1

(see [above](https://github.com/betterscientificsoftware/bssw.io/issues/2107#issuecomment-2176576984)) and I have documented that "Content Development" board and its automations [above](https://github.com/betterscientificsoftware/bssw.io/issues/2107#issuecomment-2176683256).

Any objections to me pulling the trigger and doing the migration of the "Content Development" board:

* https://github.com/betterscientificsoftware/bssw.io/projects/3

?

NOTE: Given what I learned [above](https://github.com/betterscientificsoftware/bssw.io/issues/2107#issuecomment-2176576984), we may not be able to match all of the automations but we can do the best we can. 

Let me know.  (I would like to pull the trigger on this sooner rather than later while this is fresh in my mind.)

**Comment by bartlettroscoe** [comment]
> I think we can use actions to implement the workflows where the builtins are inadequate. I can help with this, but not immediately, so we may need to operate manually for a bit.

Right!  That is what GitHub intended for more flexibility:

* https://docs.github.com/en/actions/managing-issues-and-pull-requests/using-github-actions-for-project-management

> I'm good with you going ahead with the Content board.

Okay, I will pull the trigger on that and document the current state of the workflows and the gaps.

**Comment by bartlettroscoe** [comment]
NOTE: Here is info on workflows for the new GitHub project board:

* https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects
* https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions

And it looks like there are some standard GHA for automating project board workflows in the GHA marketplace:

* https://github.com/marketplace/actions/github-project-automation

**Comment by bartlettroscoe** [comment]
Starting the migration of "Content Development" board now ...

**Comment by bartlettroscoe** [comment]
I did the migration of the board "Content Development" which is now at:

* https://github.com/orgs/betterscientificsoftware/projects/5/views/1

showing:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/9343e53f-ffbb-4621-bf56-e9433e397c32)

I set the name to "Board".  Below I describe the automations that I set to match and those that could not be matched with the built-in automation for the new GH Project boards.  Compare these automations to the old project board shown [above](https://github.com/betterscientificsoftware/bssw.io/issues/2107#issuecomment-2176683256).

----

### A) Workflows transitions set up to match the old board automations

These workflow transitions were supported by the new GH Project built-in workflows.

----

**A.1)** "Idea Backlog" automation => "Item added to the project" (New issues added to "Ideal backlog" column)

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/0f962df2-be6a-41a4-a20f-a8b709ae4197)

----

**A.2)** "Read to publish" automation => "Code review approved" (PR approved moves PR to "In progress" column)

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/440debbb-888d-4e5c-97cb-b91e41902fe6)

----

**A.3)** "Ready for digest" automation => "Pull request merged" (PR merged moved to "Ready for digest" column)

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/33952cf8-5bf5-4ecf-94f1-9936dc28781c)

----

**A.4)** "Done" automation => "Item closed" (Issue and PR closed moved to "Done" column)

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/393b0b3d-8683-4b72-b927-e8379a60640a)

----

### B) Workflow automations that do not match old board automations

These workflows will need to be automated using GHA.

----

**B.1)** "Item review" automation => **NONE** ("Pending approval by reviewer" PR added to "Item review" column)

----

### Summary

So it looks like the only project workflow that I could not get to match with the old project board implementation is the "Item review" automation shown above.  Personally, I don't know if that is worth the effort to automate.  In my opinion, when the author of a PR thinks the PR is ready to review, they should manually add the reviewer and move the PR or Issue into "Item review"

**Comment by bartlettroscoe** [comment]
@betterscientificsoftware/bssw-editorial-board 

I created a new column for the new "BSSw Internal" board called "In review" and I added this Issue that that column.

I think this is ready to be reviewed by someone else and closed if it looks good.  (I don't think any more automations are needed but we can add some later in a new issue using GHA.)

**Comment by markcmiller86** [comment]
@bartlettroscoe I read through all your notes here. Thanks for detailed notes! I was wondeering about the descriptive text that appears at the top of most columns explaining why items in the column are supposed to be there (e.g. the criteria). 

Now, it looks like that description box no longer supports markdown. It is just a basic text box. So, it looks like you added some sticky issues (my wording) at the top of each column with links to the description text.

In today's meeting, we considered moving all that text into the column's `Description` box but reformatting it so it "looks decent" there. But, I am now wondering...what are your thoughts about this? 

At the very least, I would like to adjust the existing sticky issues to just a short title such as "Column Description" which links to the description text.

**Comment by bernhold** [comment]
On other boards I've converted, I've used the concept of "draft items" on the project board itself to replace the old note cards.  These draft items are a V2 feature.  They're *not* issues -- they live only on the board -- though there is a mechanism to *convert* them into issues (which I've never used).  They seem to happily stay at the top of columns (which is something that issues don't do, and was also a perennial problem with the note cards on the classic boards.

If you click the Add item button at the bottom of a column, you'll create a draft item by detail -- you have to do more work to create anything else.

**Comment by bartlettroscoe** [comment]
I think this is done, yes?  Can we close this issue?

**Comment by bernhold** [comment]
I haven't yet had time to write the actions to put things on the boards, in the right columns and such.

I don't care whether you want to keep this open or create a new issue specifically for this task.

**Comment by bernhold** [comment]
I think we've addressed this as well as we can.  Closing
