### ISSUE TITLE
Checklist of pending EB docs items

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#634]
Following is a checklist of pending EB docs items.

- [x] Remove un-necessary files from the directory
- [x] Relative TOC and links needed in all docs
- [x] Simplify curated content style guide
- [x] Review events style guide
- [x] Review article style guide
- [x] Update curated content workflow
- [x] Complete blog workflow
- [x] Complete article workflow
- [x] Add image handling text
- [x] Add metadata section

**Comment by rinkug** [comment]
This was completed!
