### ISSUE TITLE
Create checklist for content-based bssw.io PRs and EB-docs text?

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#695]
@betterscientificsoftware/bssw-editorial-board 

It is confusing to know all what needs to be done to get new content added to the bssw.io site and how this process works with the new ["preview branch" workflow](https://github.com/bartlettroscoe/bssw.io/blob/330-preview-pr-workflow/Site/PullRequestPreviewBranchWorkflow.md) (see issue #330 and PR #694).  For example, in PR #688, it is not clear to @markcmiller86 and myself (@bartlettroscoe) what things need to get done to be able to preview the content on the https://preview.bssw.io site and get it published to the https://bssw.io as part of the PR process (using the 'preview' branch workflow).  There is some high-level documentation on the [BSSw Editorial GitHub Pages site](https://betterscientificsoftware.github.io/bssw.io/bssw_content_publishing.html) but that is hard to find and it is not specific as to the actual process.

This story is to log the conversation around adding a checklist to the bssw.io content-based PRs that lists out the needed tasks as a template when the PR first gets created.  That would help authors and EB members to be clear what needs to be done and when to make this progress go faster and smoother.

However, we also want to avoid duplication between what is documented on [EB Editorial Team Github Pages site](https://betterscientificsoftware.github.io/bssw.io/index.html) and what is listed in the detailed PR checklist.

**Comment by bartlettroscoe** [comment]
Here is a proposal for what the template checklist could look like for a content-based PR. Please provide comments in new comments below and edit this comment to update the checklist (and we can see the history of those edits so now worries).

## Proposal 1

**Checklist:**
* [ ] Review of the content (as a simple rendered `*.md` file on GitHub)
* [ ] Add meta-data to the `*.md` file (what state does it need to be in?)
* [ ] Rebuild https://preview.bssw.io site and view the new content there and how it fits into the site (including searching, etc.)
* [ ] Make any final changes in the PR needed and verify on https://preview.bssw.io it looks correct
* [ ] Merge PR (but keep the PR in "Item Review" in [Content Development](https://github.com/betterscientificsoftware/bssw.io/projects/3?) 
* [ ] Verify new new contribution shows up on https://bssw.io as expected
* [ ] Move the PR from "Item Review" to "Done"

**Comment by bartlettroscoe** [comment]
CC: @rinkug, @markcmiller86, @bernhold 

Also, related to this Issue is the problem of generated files with references called out in #330:

> Avoid having to manually hack files generated by the `wikize_refs.py` script

It occurred to me there is a simple way to solve the problem of generated files.  We (I) can develop a simple script:

```
generate_md.py <base-name>
```

that will:

* Generate `<base-name>.md` from `<base-name>-src.md` (using `wikize_refs.py`)
* Set `Publish: no` in `<base-name>-src.md`
* Set `Publish: yes` in `<base-name>.md`
* Change `<base-name>.md` to read-only

And if the user makes a mistake and the original is called `<base-name>.md` and there is no `<base-name>-src.md` file, then it will error out telling the user to rename it it `<base-name>.md`.

This solves several problems:

* Avoid people accidentally editing the generated file (because it is read-only)
* Needing to do something after the PR branch merged to 'master' (because `Publish: yes` is already set)
* Needing to remove the source file so it will not get published as well (because  `Publish: no` is set and therefore it will not be rendered on the sites preview.bssw.io or bssw.io)

So I propose to  put in a PR that:

* Adds the script `generate_md.py` (under `bssw.io/utils/` and move `wikize_refs.py` there as well?)
* Adds a PR template with the checklist shown [above]() with mention of the usage of generated files with references and `generate_md.py`
* Updates any of the EB docs that describe this process

Okay?

**Comment by markcmiller86** [comment]
FYI...there is more discussion on the wikized references issue in #363. Something similar to the above was proposed there.

To be honest, its been my impression that this whole wiki-like referencing thing I started wasn't necessarily seen as a step in a positive direction at least not for the *key* content we really need to support here nor did I have the impression the rest of the team found it necessary.

I think I've been the only one to author content using it (maybe @bartlettroscoe did one article too) and I was thinking maybe we need to totally abandon this wiki-like referencing stuff.

More recently, I've opted not to develop content using it and was surprised when I was asked to go back to the Pull Request Size article and use it there. In my original draft, I just used basic in-line style links but was asked to reformat them all to this wiki-like referencing approach a couple of weeks ago. I didn't think that was necessary then but dutifully complied anyways.

I am fine with simply abandoning it instead.

**Comment by bernhold** [comment]
We probably need to have a team discussion about this to reach closure.

But the advice that we got from our design consultant (Matt at Sandbox Studios), we should generally prefer *not* to have references -- they increase the cognitive load on readers.  BSSw articles are meant to be relatively easy reading.  They're definitely not meant to be at the level of a scientific paper or such.

That said, there will be the occasional situation where we references are justified/needed (various possible reasons).  When they are, there have been a couple of different strategies we've used to deal with them, depending on the situation.

I don't think we want to completely abandon the ability to wikiize, but I think we want to put the threshold pretty high for using it.  I think the discussion would be about the various use cases where references are appropriate, and methods for dealing with them.

**Comment by bartlettroscoe** [comment]
@markcmiller86 

> I think I've been the only one to author content using it (maybe @bartlettroscoe did one article too) and I was thinking maybe we need to totally abandon this wiki-like referencing stuff.

Right, I forgot about #363.  That issue is about `wikize-refs.py` while this issue #695 about the whole content development process (of which `wikize-refs.py`  is just one option).

Personally, I think it is quite valuable to have a tool to manage references for `*.md` files.  While I have not always used the tool (due to the hassle of having to deal with two copies of the file in the repo and the `Publish` problem), I think the general tool/approach is great (i.e. a simple bibtex for `*.md` files).  We just need a way to make having these generated files work smoothly.

Also, given the general impression that people wanted to see a reference list for articles like in PR #670 (after I could have sworn that people said they did **not** want to see a reference list), it seems we should not dismiss this so fast (since you used the tool for the very reason that it is hard to manage a longer list of references in Markdown).

I suspect that more people would use this tool to manage references if we addressed the problems mentioned in #330, #363 and above, by taking an approach like mentioned [above](https://github.com/betterscientificsoftware/bssw.io/issues/695#issuecomment-) and made it super easy to use.  And I think this could even be broken out into its own little GitHub repo and get usage outside of bssw.io.  This is a recognized and unsolved problem from what I can see (e.g. take a look at [zotero](https://www.simondcoll.com/references-markdown-zotero/), [latex and panadox](https://amelon.org/2018/03/13/md-reference.html).  Those are very heavyweight solutions.  What we want is something very simple and lightweight.  That is `wikize-refs.py`.

But still, people can choose to use it or not.  For a small number of references, doing them by hand using what `wikize-refs.py` generates, like I did in [WorkingEffectivelyWithLegacyCode.md](https://github.com/betterscientificsoftware/bssw.io/blob/master/CuratedContent/WorkingEffectivelyWithLegacyCode.md), is no big deal.  But if we deal with the obvious problems mentioned above, I would use it for every article that has references (because it would be easier overall which is not the case right now if you just have a few references).

Again, I am willing to put in a PR that implements the proposal [above](https://github.com/betterscientificsoftware/bssw.io/issues/695#issuecomment-772784662) along with a PR template with a checklist.  But if I am the only person who thinks this useful, I will not bother.  (In which case we should stop using `wikize-refs.py` or just use it offline and don't commit the source file.)

**Comment by bartlettroscoe** [comment]
> But the advice that we got from our design consultant (Matt at Sandbox Studios), we should generally prefer not to have references -- they increase the cognitive load on readers.

@davidbernholdt, but is that true for the way that `wikize-refs.py` does the references?  They are just a small superscript numbers and if you hover you mouse over the superscript you get the title of the reference.  Personally I think that is less distracting that having a bunch of hyperlinked text.  For example, I think the [wikized-ref version](https://github.com/betterscientificsoftware/bssw.io/blob/16c216a6b23f0e275ead94b0f84ee42b3a190a28/Articles/ShortArticles/PullRequestSizeConsiderations-wikized.md) looks better than the [in-text hyperlinked version](https://github.com/betterscientificsoftware/bssw.io/blob/efcd269c09e5688c364d76ca068e3c60c862b039/CuratedContent/PullRequestSizeConsiderations.md) of #670.  That might just be my opinion.

Personally I am more interested in (reading and writing) fewer more thoughtful and deeper articles like #670 than a bunch of thin more superficial curated content articles.  And the former begs for references.  Again, just my opinion.

**Comment by bernhold** [comment]
@bartlettroscoe from Matt's perspective, it should be our general rule.

However, we don't always have to take Matt's advice.  I understand your thinking that more substantive article would warrant (more) references.  That's certainly where I would consider them most likely to be needed/warranted.

And so, the suggestion that we discuss as a group...

**Comment by bartlettroscoe** [comment]
Just some more background before we talk as a group ...

Here is some evidence that the more subtle references produced by `wikize-refs.py` might provide better reading comprehension compared to hyperlinked text:

* https://www.psychologytoday.com/us/blog/your-childs-brain-and-behavior/201701/the-effects-digital-technology-reading?amp

See section "2. Reading on a screen makes it harder to navigate and orient oneself, especially with hypertexts" which ends with:

> These negative effects of hypertext reading are not inevitable, though. Using a navigational support structure may be helpful.

I think that is what having a list of references at the bottom (out of the way of the main text) does for you.  I think it is also why a list of references at the end is better than footnotes littered all over a document as a means to provide references without distracting from the main flow of the text.

This would seem to go against the advice of the contactor (unless they are suggesting no references at all, hyperlinked or not).

> And so, the suggestion that we discuss as a group...

I actually need to miss the first 60 minutes of the bssw.io hackathon meeting tomorrow.  Perhaps we can discuss as a group the following week?

**Comment by markcmiller86** [comment]
> And I think this could even be broken out into its own little GitHub repo and get usage outside of bssw.io

Funny you should mentione that...I've been thinking about doing that since I wrote it. But, there are a few improvements I'd make to it before I did.

**Comment by bartlettroscoe** [comment]
FYI: The latter commits in https://github.com/betterscientificsoftware/bssw.io/pull/670/commits show just how confusing having both the source and the generated files in the repo can be without a clear checklist of what edits to make in which file.  For example, see https://github.com/betterscientificsoftware/bssw.io/pull/670/commits/e181ff1ddb93fd03ed05f549faa3945b45b290a1 where the commit author set `Publish: preview` in the source file by mistake.

**Comment by markcmiller86** [comment]
Just a comment regarding checklist in a template...best to use reference style links as is demonstrated here in this comment, below. It reduces wordiness and repetitiveness.

## Proposal 1

**Checklist:**
* [ ] Review of the content (as a simple rendered `*.md` file on GitHub)
* [ ] Add meta-data to the `*.md` file (what state does it need to be in?)
* [ ] Rebuild [preview] site and view the new content there and how it fits into the site (including searching, etc.)
* [ ] Make any final changes in the PR needed and verify [preview] looks correct
* [ ] Merge PR (but keep the PR in "Item Review" in [content development]
* [ ] Verify new new contribution shows up on https://bssw.io as expected
* [ ] Move the PR from "Item Review" to "Done"

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[content development]: https://github.com/betterscientificsoftware/bssw.io/projects/3?

**Comment by bartlettroscoe** [comment]
I think with the merge of PR #718 that gives `wikize_refs.py` and in-place update option, all of the issues related to managing a sperate source and generated file are gone.  For local development and debugging purposes, `wikize_refs.py foo.md` by default generates a separate `foo-wikizied.md` file so it super safe to use if the user does not know what they are doing.  But when we are ready to post a PR, we can run `wikize_refs.py -i foo.md` and commit the wikized file ready to publish.  This is about the perfect workflow.

So the updated checklist would be:

## PR Checklist Proposal 2

**Checklist:**
* [ ] Review of the content (as a simple rendered `<base>.md` file on GitHub).
* [ ] If using `wikize_refs.py`, only commit the in-place updated file with `wikize_refs.py -i <base>.md`.
* [ ] Add meta-data at bottom to the `*.md` file and set `Publish: preview`
* [ ] Rebuild https://preview.bssw.io site and view the new content there and how it fits into the site (including searching, etc.)
* [ ] Make any final changes to `<base>.md` (and update references with `wikize_refs.py -i <base>.md` if using them) in the PR needed and verify on https://preview.bssw.io it looks correct.
* [ ] Change meta-data to `Publish: yes` if the document is fully ready to publish (otherwise, leave `Publish: preview` if a post-merge review must be done).
* [ ] Merge PR (but keep the PR in "Item Review" in [Content Development](https://github.com/betterscientificsoftware/bssw.io/projects/3?).
* [ ] Verify new new contribution shows up on https://bssw.io as expected.
* [ ] Move the PR from "Item Review" to "Done".

**Comment by bartlettroscoe** [comment]
Related to my epic SEPW-211

**Comment by bartlettroscoe** [comment]
Related to #744, I am working on this now.  I will create three different minimal PR templates for:

* bssw.io content
* bssw.io content with formal citations (i.e. using `wikize_refs.py`)
* content not viewed on bssw.io (i.e. not merged to the 'preview' branch)

**Comment by bernhold** [comment]
@bartlettroscoe I would modify the end of your checklist (in **bold**)...

**Checklist:**
* [ ] If using `wikize_refs.py` to manage references, only commit the in-place updated file using `-i`.
* [ ] Review of the content (as a simple rendered `*.md` file on GitHub).
* [ ] Add meta-data to the `*.md` file (set `Publish: preview`).
* [ ] Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [ ] Make any final changes in the PR needed and verify [preview] looks correct (remembering to update `*.md` file with  `wikize_refs.py -i` if references are being used).
* [ ] Change meta-data to `Publish: yes` if the document is fully ready to publish.
* [ ] **Move the PR to "Ready to Publish" in [content development].**
* [ ] **Assign to one of the site maintainers to carry out final publication steps.**
* [ ] **Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).**
* [ ] **Merge PR. Should automatically move to "Done" in [content development].**
* [ ] Verify new new contribution shows up on [bssw.io] as expected.

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[content development]: https://github.com/betterscientificsoftware/bssw.io/projects/3?

The "site maintainers" bit needs to be better defined.  What we have now are a subset of the BSSw Team who know the process to login and rebuild the production site.  In theory we could open this up to the whole EB, though being the production site, we've kept it to a smaller group of people to date.

**Comment by bernhold** [comment]
I see that teams can be assigned as reviewers, so I propose that the "site maintainers" be a team defined for the repository, and instead of assigning, a review is requested of them. (This is after other reviews are done.)

**Comment by bartlettroscoe** [comment]
Now that PRs #718, #750 and #765 has been merged, we have a PR template with a a checklist that lists what needs to be done to review and publish content to the bssw.io site (including the usage of `wikize_refs.py` and formal citations).  There is a little cleanup to do (i.e. #769 and #770) but those can be handled in those PRs.

I think this is ready to close.

**Comment by bartlettroscoe** [comment]
With the merge of PRs #765 and #711, we have a PR template in place with checklist.  We can improve on that template in follow-up Issues and PRs.  Closing this Issue as complete.
