### ISSUE TITLE
EPIC: Working Group: References

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#702]
Charter: When is it appropriate (useful) to use references in BSSw resources and how should they be styled/presented?

Members: @markcmiller86, @bartlettroscoe, @JeanShuler 

Child Issues: #363, #695, #770

## Tasks

* [x] Discuss and come up with proposal for policies on using references/citations in bssw.io content
* [x] If to allow include of references/citations, determine how references should be handled:
  * [x] Determine if in-text hyperlinks are okay or if systematic references/citations should be preferred?
  * [x] If used, determine the usage of `wikize_refs.py` for managing references/citations:
    * [x] Should, its usage optional and ordained by BSSW?   => If using formal citations, must use references/citations consistent with `wikize_refs.py`.
    * [x] How to handle he source and generated files? => Use in place updates of the references/citations (see PR #718)
* [x] Create a PR that updates the EB docs with the proposed policy and process on the handling of references/citations ...**See PR #750**
* [x] Ask @betterscientificsoftware/bssw-editorial-board members to review PR #750.
* [x] Get back review from @betterscientificsoftware/bssw-editorial-board members for PR #750.
* [x] Move section on citations/references from `bssw_styling_originalarticles.md` to `bssw_styling_common.md` and add sections to `bssw_styling_curated.md` and `bssw_styling_event.md` discouraging formal citations (see #769) ... **See PR #778 ...**
* [x] Run `wikize_refs.py` on all existing `<base>-wikized.md` files, remove matching `<base>.md` files, and rename `<base>-wikized.md` files to `<base>.md` ... **See #779 ...**

**Comment by bartlettroscoe** [comment]
@markcmiller86, @bartlettroscoe, @JeanShuler,

FYI: I added a task list [above](https://github.com/betterscientificsoftware/bssw.io/issues/702#issue-806666108) to guide this effort.

My views on this are given in #363 and #695.  To summarize my opinions on this:
* We should allow references when they make sense.  (For short CC articles, usually not needed since the reference is given at the top.  For articles where there should be more than one reference, don't discourage their usage).
* If using references, the more systematic and less obtrusive references produced by `wikize_refs.py` should be used over hyperlinked text.
* It would be best **not** to commit the generated file produced by `wikize_refs.py` but have it generated as needed (but I realize that may be hard given the current web hosting contractor being used and how the 'preview.bssw.io' site is not getting updated frequently).
* If the source and the generated files are both under version control (which seems most reasonable right now):
  * Come up with a naming convention for the source and generated files and stick to it (i.e. `<base>-src.md`/`<base>.md` or `<base>.md`/`<base>-wikiized.md`).
  * Only edit the source file, never the generated file.  (If someone accidentally edits the generated file, move those changes over to the source file right away and stick with modifying the source file from there.)
  * Set the `Publish` attribute to `no` in the source file (always) and set to `preview` or `yes` in the generated file (depending on if the final review and editing can be pre-merge or not).

Please provide feedback, other opinions, etc. in new comments below this one.

**Comment by bartlettroscoe** [comment]
@markcmiller86, @JeanShuler (my co-team members on this task),

FYI: I updated my proposal for the proposed tool `generate_md.py` in https://github.com/betterscientificsoftware/bssw.io/issues/695#issuecomment-772784662 that takes into account:

* The title in the source file  `<base-name>-src.md` has to be different than in the generated file `<base-name>.md` or the web contractors site generator may pick the file `<base-name>-src.md` by accident instead of the file  `<base-name>.md` to display (or not depending on the value of `Publish`).
* You can't make  a file in Git read-only.  Therefore, we just need to make it clear in the PR checklist that people should not be manually edit the generated file `<base-name>.md`, only the source file `<base-name>-src.md`.

Given the confusion and back and forth going on with PR #670, I would like to take as stab at this checklist and the script `generate_md.py`.  Any objections for me putting in a PR that includes `generate_md.py` and a PR checklist for its usage?  (In fact, we could different checklists for PRs that use `generate_md.py` and those that do not to make this more clear.)

**Comment by bernhold** [comment]
Is it possible to do the wikiization in place?  The script would need to recognize where processing has already been applied and not change that.  Maybe thinking of it as a (potentially) incremental process (add a reference, reprocess to wikiize the new reference).

**Comment by markcmiller86** [comment]
> Is it possible to do the wikiization in place? 

Maybe. But, the markdown structure of the file is changed significantly. We could bracket sections of the file NOT to re-process (in any subsequent invokations) using some xml comments maybe like `<!--- BEGIN GENERATED BLOCK --->` and `<!---END GENERATED BLOCK --->` and that could probably work to prevent the `wikize-refs.py` script from processing that section of the file. I kinda like that idea.

**Comment by markcmiller86** [comment]
@bartlettroscoe I am fine with proceeding as described in [#695 comment](https://github.com/betterscientificsoftware/bssw.io/issues/695#issuecomment-772784662). 

I do like @bernhold suggestion to see if we can handle in place. I can spend some time working on that in `wikize-refs.py` if that would help. I think it might.

**Comment by bernhold** [comment]
@markcmiller86 I am afraid that the comment-based blocking will cause problems.  If you added a reference in the middle of that block, it sounds like things would be messed up -- with the block in place, the new ref wouldn't be processed, but without it stuff that's already been processed might get messed up.

The script really needs to be idempotent at a finer level of granularity.  Maybe I need to sit down and take a closer look at the before and after and think about this suggestion myself.

**Comment by markcmiller86** [comment]
Hmmm...I don't think I agree with that.

Maybe a different mechanism is better. Here's the basic problem. Markdown [reference links](https://github.github.com/gfm/#reference-link) are the basic issue here. The goal is to ensure the list of reference *definitions* explicitly appear in the markdown file as a table of references.

So, a whole block of link *definitions* (which ordinarily remains hidden) gets slurpped up and then re-emitted to the file in two copies; one copy is a new list of link *definitions* which are all internal to the table of references and the other is the actual table. If we agree that someone will only ever edit the original link definitions, then we can make the tool ignore that reformatted stuff each time it is re-run.

Let me work on the script a bit to convince myself I can make it work.

**Comment by markcmiller86** [comment]
Ok, I have a version of `wikize_refs.py` that works in place. It can be invoked repeatedly on the same file, replacing that file, and its output is unchanged if the input is unchanged. It will do everything as before.

The only caveat is that if you as an author need to edit references *after* `wikize_refs.py` has been invoked on the file, you will be doing so in what appears to be a section of the file that has been commented out by lines of the form `<!--- BEGIN LINK DEFINITIONS` and `END LINK DEFINITIONS --->`.

**Comment by bartlettroscoe** [comment]
> Ok, I have a version of wikize_refs.py that works in place. It can be invoked repeatedly on the same file, replacing that file, and its output is unchanged if the input is unchanged. It will do everything as before.

@markcmiller86, that sounds like a great solution.  And having the references you edit commented out seems fine.  Can I take a look at the updated script?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I am fine with proceeding as described in #695 comment.

@markcmiller86, a `wikize_refs.py` script that updates the file in place greatly simplifies things.  If we can get that new version and ensures that it works as it should (and I can write some automated tests for it), then the process becomes much easier and we don't need anything other than `wikize_refs.py`.

**Comment by bartlettroscoe** [comment]
References Working group members (@markcmiller86, @bartlettroscoe, @JeanShuler),

We should meet to recommend a policy on references in bssw.io documents.  I will contact you offline by email to try to set up a short meeting to discuss this and come up with our recommendations to present to the full editorial team.

**Comment by markcmiller86** [comment]
Hmmm...do we need to actually meet? How about this policy draft.

> This policy applies to the *formal* style for handling referenced material as demonstrated in [this example](https://github.com/betterscientificsoftware/bssw.io/blob/master/Articles/Blog/ApolloGuidanceComputerPart1-wikized.md). It does *not* apply for the typical cases of handling in-line *links* in content.

> In general, bssw policy is to discourage the use/need for *formal* references in its content. That said, we recognize there may be occasions where bssw editorial board members or authors feel strongly that references are needed for a given piece of content. The decision to *allow* or *require* references is one that should be agreed upon by the author and EB members prior to developing the content. When references are to be used, we require author's to follow the guidelines described [here](https://github.com/betterscientificsoftware/bssw.io/blob/master/Articles/Blog/ReferencesInMarkdownHybridApproach.md).

**Comment by markcmiller86** [comment]
Note, the guidelines document linked in the above policy statement draft is old. It is updated in #718

**Comment by bartlettroscoe** [comment]
> Hmmm...do we need to actually meet? How about this policy draft.

As per https://github.com/betterscientificsoftware/bssw.io/pull/718#issuecomment-786821061, @bernhold suggested we should meet.  But I guess we can discuss in comments like were are here.  (But if there is too many comments and back and forth, it will save us time if we just have a short meeting.)

I don't 100% agree with **Reference Policy Proposal 1** given [above](https://github.com/betterscientificsoftware/bssw.io/issues/702#issuecomment-786960868).  Instead, I would have the policy state:

## Reference Policy Proposal 2

> Most simple curated content documents only have a single external reference and therefore don't need any formal references (beyond the single reference in the header of those pages).  Short documents with a small number of simple online external references can use in-text hyperlinks.  However, if multiple external references are made in a longer document, then it is encouraged to use the less intrusive [reference links](https://www.markdownguide.org/basic-syntax#reference-style-links) of the form generated using the `wikize_refs.py` tool in order to improve readability and reading comprehension (see [The Effects of Digital Technology on Reading](https://www.psychologytoday.com/us/blog/your-childs-brain-and-behavior/201701/the-effects-digital-technology-reading?amp)).

@JeanShuler, do you have an opinion?

**Comment by markcmiller86** [comment]
@bartlettroscoe I like yours too. I think we can merge the two. Items in **bold** below are the key points.

Mine is aimed at **discouraging** them but **allowing** for them for some occasions (biased that direction based on prior comments from @bernhold) where they are deemed needed (by **judgement** of author and/or EB members) and it requires that there be some **agreement** for this need reached prior to drafting the content. Mine then also references the **doc guidelines** I've written.

Your is aimed at **acknowledging** most content **does not need formal refs** and hyperlinks are usually fine but otherwise **encouraging** them when there are **multiple** (do you simply mean more than one?) external references and providing some (**stylistic**-based) rationale for their use, apart from any author or EB member preference or judgement that they are needed. 

> As an aside, you will recall a few weeks ago I wrote the [article on pull request size](https://github.com/betterscientificsoftware/bssw.io/blob/master/Articles/ShortArticles/PullRequestSizeConsiderations.md) using only hyper-links and was then asked by EB to reformat with refs instead. Was that a judgement call on part of EB or was there indeed a stylistic reason for requesting that?

I think we differ only in the *slant* (encouraging or discouraging). And, I am honestly fine with encouraging. FWIW, I seem to have found the need to use them more often than not :smile:.

Also, it occurs to me the correct terminology here is *citations*, right? If so, we should change our verbiage in the policy to use that instead of *reference* and its derivatives. For now, I'll continue with *reference*.

### Proposed Merged Policy

> Certain content types on [bssw.io](https://bssw.io) do not require formal reference styling (e.g. formal *citations*) either because the format is highly constrained (e.g. Events, Curated Content) or because the document is short and uses only a small number inlined hyperlinks. However, there are circumstances where formal reference styling is warranted. These include...

> * larger documents with *many* references can benefit from formal reference styling to improve [readability and reading comprehension](https://www.psychologytoday.com/us/blog/your-childs-brain-and-behavior/201701/the-effects-digital-technology-reading?amp)).
> * a document needs to reference multiple off-line materials (e.g. books) for which there is no, reliable on-line proxy.
> * EB members and/or authors feel strongly that references are needed to support a given piece of content (e.g. the Covid19 article).

> The decision to *allow* or *require* references is one that should be agreed upon by the author and EB members prior to developing the content. When references are to be used, we require authors to use the less intrusive [reference links](https://www.markdownguide.org/basic-syntax#reference-style-links) and to follow the guidelines described [here](https://github.com/betterscientificsoftware/bssw.io/blob/master/Articles/Blog/ReferencesInMarkdownHybridApproach.md)

**Comment by bartlettroscoe** [comment]
@markcmiller86, I like the Proposed Merged Policy [above](https://github.com/betterscientificsoftware/bssw.io/issues/702#issuecomment-787012416).

@JeanShuler, do you have an objection to this proposed merged policy?  If not, I think we can recommend this to the BSSW Editorial board.

**Comment by markcmiller86** [comment]
> @markcmiller86, I like the Proposed Merged Policy [above](https://github.com/betterscientificsoftware/bssw.io/issues/702#issuecomment-787012416).

Great...while we await @JeanShuler response, there is one remaining question. What do we call this *stuff*. We've been using "references". I wonder if "citations" is better?

**Comment by bartlettroscoe** [comment]
>  What do we call this stuff. We've been using "references". I wonder if "citations" is better?

The term "citations" is likely better.  The work "references" is a bit to overloaded.

**Comment by prwolfe** [comment]
Agreed.

Thanks for working this guys.

Paul

**Comment by JeanShuler** [comment]
I also think Citations is a better choice.
Jean

**Comment by JeanShuler** [comment]
Sorry I haven't been responsive!  I am fine with the  proposed merged policy so please recommend this to the BSSW Editorial board.

**Comment by bartlettroscoe** [comment]
Working group members (@markcmiller86, @JeanShuler),

With everyone signing off on the **Proposed Merged Proposal** for the handling of references/citations listed [above](https://github.com/betterscientificsoftware/bssw.io/issues/702#issuecomment-787012416), I think next task is to create a PR with the proposed policy so the the EB members have something solid to review.  I updated the list of "tasks" accordingly as shown [above](https://github.com/betterscientificsoftware/bssw.io/issues/702#issue-806666108).

Any objections?  If not, I will post a PR with the **Proposed Merged Proposal** for the handling of references/citations listed [above](https://github.com/betterscientificsoftware/bssw.io/issues/702#issuecomment-787012416).

**Comment by JeanShuler** [comment]
No objections!  Please post a PR with the proposed merged proposal.

**Comment by markcmiller86** [comment]
Thanks @JeanShuler and @bartlettroscoe ... no objections. Please proceed.

**Comment by bartlettroscoe** [comment]
>  Please proceed.

Okay, I will try to find a reasonable place to put this policy in the current EB Docs files and post a PR.

**Comment by bartlettroscoe** [comment]
FYI: I think with the merge of PR #718 that gives `wikize_refs.py` and in-place update option, all of the issues related to managing a sperate source and generated file are gone.  I will now post a PR for the updated policy on the usage of references/citations and the (optional) usage of the tool `wikize_refs.py`.

**Comment by bartlettroscoe** [comment]
Related to my epic SEPW-211

**Comment by bartlettroscoe** [comment]
@betterscientificsoftware/bssw-editorial-board 

FYI: I posted PR #750 that has the updated policy on citations/references.  Please review.

**Comment by bartlettroscoe** [comment]
It just occurred to me that as part of this, after we merge PR #750, we should do the following:

* Run `wikize_refs.py` on all existing `<base>-wikized.md` files, remove matching `<base>.md` files, and rename `<base>-wikized.md` files to `<base>.md`.

That will make all of the `*.md` files in the repo compliant with the new policy.

**Comment by bartlettroscoe** [comment]
With PR #778 posted to address #769, the last thing to do to close this issue is to:

>  Run `wikize_refs.py` on all existing `<base>-wikized.md` files, remove matching `<base>.md` files, and rename `<base>-wikized.md` files to `<base>.md`.

I tried that but ran into errors.  I posted #779 to address that.

**Comment by bartlettroscoe** [comment]
I just realized that the comment https://github.com/betterscientificsoftware/bssw.io/issues/779#issuecomment-840167855 is better put in this issue ...

@markcmiller86, one of the goals of #779 is to eliminate the duplicate `<base>.md` and `<base>-wikized.md` files.  So can we just delete all of the remaining `<base>.md` files and rename the existing `<base>-wikize.md` files to `<base>.md`?  The old source `<base>.md` files will still be in the git history if we need them.  That way, people will not be confused by two sets of files `<base>.md` and `<base>-wikized.md`.  Okay?
