### ISSUE TITLE
Working Group: Merging images repository

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#703]
Charter: Plan and implement merging the images repository into the bssw.io repository.

Members: @bernhold, @bartlettroscoe, @prwolfe 

Note that all references to images will need to be modified.  This is primarily in blogs, but possibly in other content as well.  Also in the Site directory, Fellowships, etc.

## Tasks

* [x] Check to see if git-lfs is a viable option:
  * [x] Can everyone get git-lfs installed on their own machines (including authors of articles)?
  * [x] Is the web hosting contractor okay with installing git-lfs and using it on their servers? **=> No, they can't.  Therefore, we can't use git-lfs for the bsswi.o repo!**
* [x] Come up with a policy for storing images in the main 'bssw.io' repo (e.g. Do they sit beside their `<base-name>.md` file? Do they live in a `<base-name>/` subdir beside their `<base-name>.md` file? Do they live in a shared `bssw.io/images`/ subdir?) **=> Seems the web contactor wants them to be in a single directory `bssw.io/images`/.**
* [ ] Create a trial branch and PR with a single image file under `bssw.io/images/` and an `*.md` file the references so it will merge to the `preview` branch and be displayed on preview.bssw.io.
* [ ] Write scripts that will do the translation from the separate 'images' repo into the 'bssw.io' repo and update all of the references in the `*.md` documents (and have the scripts reviewed).  (This script should be run on 'preview' branch to get the full list of images but the commits should be done on a branch off of 'mastesr'.)
* [ ] Create a PR with updated EB docs, PR checklist, etc. for the updated handling of 'images' (and have it reviewed).
* [ ] Review the plan to do the translation with the entire @betterscientificsoftware/bssw-editorial-board team (also pointing to the PR with the updated documentation).
* [ ] Make sure that the web hosting contractor is setup on their end ready for the change (i.e. we can see the image file in that trial PR on the preview.bssw.io site).
* [ ] Send out an announcement to the web hosting contactor and the IDEAS team that the translation will take place at a given date and time.
* [ ] Perform the translation:
  * [ ] Run the translation scripts to copy images into the 'bssw.io' repo (run on 'preview' branch to get list of images)
  * [ ] Push the updated 'master' branch of to the 'bssw.io' repo.
  * [ ] Make the existing 'images' repo read-only for now (and potentially rename it and/or make it private, but don't delete for now).
  * [ ] Merge the PR with the updated EB docs, PR checklist, etc. for the handling of 'images'.
  * [ ] Update and verify that the 'preview.bssw.io' and 'bssw.io' sites are rendering the images correctly.
* [ ] Sent out announcement that translation is complete.
* [ ] Create at least one new PR with new content with images and test the updated process.
  * [ ] Verify that the 'preview.bssw.io' site is showing the images in the new content.
* [ ] Mark as DONE!

**Comment by bernhold** [comment]
Additional questions that came up during EB meeting discussions:
1. Do we want to impose consistent file naming conventions?
2. Should we implement with LFS?

**Comment by bernhold** [comment]
> 1. Do we want to impose consistent file naming conventions?

Personally, I believe we should get the move done and possibly worry about file naming conventions later as a separate question (and possibly also encompassing text content as well as images)

**Comment by bernhold** [comment]
> 2. Should we implement with LFS?

@bartlettroscoe observes that the images repo is currently 247 MB, which is not large by Git or GitHub's standards. @markcmiller86 notes that it might matter for bandwidth (LFS files don't count against bw).

He also notes that git-lfs does not work with GitHub pages.  And we would need to ensure that the production and preview sites are using lfs-enabled git if we wanted to change.

**Comment by bartlettroscoe** [comment]
@bernhold, @bartlettroscoe, @prwolfe, I created a detailed list of tasks [above](https://github.com/betterscientificsoftware/bssw.io/issues/703#issue-806671486) to get this done. Please review that checklist and comment here if you see any problems with this.

The first thing to do are to see if git-lfs is an option.#670 

@davidbernholdt, can you please contact the web hosting contractor and see if they are okay with git-lfs?  They will need to install the `git-lfs` binary on all of their servers and run `git lfs install` in the user accounts of every account that will interact with the repo on all of their servers.  See https://git-lfs.github.com/.

After that, we need to see if all of the IDEAS team members (and potential authors) or okay with using git-lfs?

NOTES:
* If you are not touching or needing to view image files managed with git-lfs, then you don't need to have git-lfs installed.  (Those files will just show up as a type simple text file with info about the file they represent.)  So every author would not need to bother with git-lfs for thier contribution (only those that involve images).
* git-lfs is usually available as a binary for every system.  (I even installed it for Windows and used it with cygwin git.)

**Comment by bernhold** [comment]
From Clara:
> I think this should be fine. The front-end references images by URL, so as long as the references point to valid URLs (generally GH raw URLs) everything should work. Let us know when you introduce this so we can double-check, though. 

@bartlettroscoe do you have an LFS repo handy that you could check what the "raw" link to an LFSed asset looks like?

**Comment by prwolfe** [comment]
I would want to stay with github-pages unless we have another compelling reason to change.

Paul

**Comment by bernhold** [comment]
@prwolfe made me think deeper about LFS.  GH-pages is not compatible with LFS.  We do actually use GH-pages now for the EB docs and related.  I think we want to keep being able to do that, and I think we want to be able to easily include images there, as appropriate.

I think it would be easy to designate a different directory for EB docs images vs BSSw.io images.  But how easy is it to get LFS to differentiate?  Can you control LFS by path?  The only thing I've seen is which file extensions to use LFS for, and I've never seen any way to exempt parts of the tree from that.

**Comment by bartlettroscoe** [comment]
> I would want to stay with github-pages unless we have another compelling reason to change.

@prwolfe, the bssw.io site is not a GitHub pages site so this does not apply to any images being shown from the site 'bssw.io' currently.  This was just a comment about what would happen if we wanted to changes 'bssw.io' to a GitHub Pages site in the future.  (But by that point, GitHub Pages may support git-lfs so it may be mute issue.  And if not, we can always transition back to not using git-lfs if we want.)

> I think it would be easy to designate a different directory for EB docs images vs BSSw.io images. But how easy is it to get LFS to differentiate? Can you control LFS by path? The only thing I've seen is which file extensions to use LFS for, and I've never seen any way to exempt parts of the tree from that.

@bernhold, right, but you can apply git-lfs at the directory level.  The issue with git-lfs **does** apply to any images used in the EB docs site:

* https://betterscientificsoftware.github.io/bssw.io/

but there are not many images there that I can see:

```
$ cd bssw.io/

$ find docs/ -name "*.png"
docs/images/company_logo.png
docs/images/company_logo_big.png
docs/_site/images/company_logo.png
docs/_site/images/company_logo_big.png
```

and they are all under the `bssw.io/docs/` directory.

We can handle that by using a different `.gitattributes` file for the `bssw.io/docs/` directory from the `bssw.io/images/` directory.  So I think we can support but the 'bssw.io' site (and 'preview.bssw.io' site) that uses git-lfs for image files and the EB Docs GitHub Pages site that does **not** use git-lfs for image files.  See:

* https://git-scm.com/docs/gitattributes
* https://stackoverflow.com/questions/57595420/can-i-exclude-some-files-from-git-lfs

The official documentation says:

> When deciding what attributes are assigned to a path, Git consults $GIT_DIR/info/attributes file (which has the highest precedence), .gitattributes file in the same directory as the path in question, and its parent directories up to the toplevel of the work tree (the further the directory that contains .gitattributes is from the path in question, the lower its precedence). Finally global and system-wide files are considered (they have the lowest precedence).

So I think we are fine here by providing a different `.gitattributes` for the different base directories.  Anyway, this is easy to verify with a simple experiment.

**Comment by bernhold** [comment]
BTW, @bartlettroscoe can you please try to use only @bernhold for me.  I do have another account for testing purposes.  But I can't access that mailbox from my ORNL system, so it is not convenient.  I know it is confusing, and it creeps in easily via autocomplete. But if you can try, it would help. Thanks (I probably should have chosen a completely orthogonal username for the other.)

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe do you have an LFS repo handy that you could check what the "raw" link to an LFSed asset looks like?

@bernhold, as long as the "raw link" can be a local file reference, it should be fine.  I don't think you can point to an image file on GitHub and expect to get the entire file.  The key is that when they run any git commands locally, they must have git-lfs installed on that system.  If that is the case, then git will make sure the full real file shows up in the directory tree where it should.  So can you check to make sure they can install git-lfs on their servers?  Info is at:

*  https://git-lfs.github.com/

> @bartlettroscoe can you please try to use only @bernhold for me.

@bernhold, thanks for the comment.  I did not even notice the other one got selected (or that there was a second account).  I will fix it above and watch for this in the future.  (There are other people that have multiple github accounts and it is very confusing to know which one you should use.)

**Comment by bernhold** [comment]
> @bernhold, as long as the "raw link" can be a local file reference, it should be fine. I don't think you can point to an image file on GitHub and expect to get the entire file. 

That is exactly what they expect currently.  For example, the URL on the production site for the hero image for the latest blog article is https://github.com/betterscientificsoftware/images/raw/master/Blog_0221_Agile.png

**Comment by bartlettroscoe** [comment]
> That is exactly what they expect currently.

@bernhold, it is critical that the generated HTML points to the locally cloned image file, not a URL on GitHub.  We need to make sure that is the case (or they need to make their setup more flexible to allow that).

**Comment by markcmiller86** [comment]
I suspect all the bases regarding LFS issues have been covered here but wanted to provide a [link](https://visit-dav.github.io/largedata/help/about-download-links.html) to some notes (though the context is slightly different) I wrote for another project in case they are useful. Those notes explain the difference between the LFS *pointer* file and its *target* (the actual binary file) as well as how to specify URLs that reference the *target* (what people have been referring to as the *raw* file here).

I suspect this note from @bartlettroscoe...
>@bernhold, it is critical that the generated HTML points to the locally cloned image file, not a URL on GitHub. We need to make sure that is the case (or they need to make their setup more flexible to allow that).

is about being able to easily author markdown content that refs a locally known image file (e.g. `![](../images/foo.png`) without having to a) specify a GitHub *raw* URL for it and b) having to already have it uploaded to GitHub so that you can c) preview the site locally even when some of the (proposed) images are known only locally. Is that right?

If so, I believe that problem can be handled ensuring we have local-specific logic we can trigger when doing local preview. I do this in other Jekyll-based projects with a command like so
```
bundle exec jekyll serve --config _config.yml,_config_dev.yml
```
where `_config.yml` contains the live site generation logic (and is triggered whenever GitHub pages regenerates) and `_config_dev.yml` contains local overrides. That way, a path of the form `![](../images/foo.png)` in a markdown file can be processed by Liquid during GitHub pages site gen and turned into a *raw* URL for the live site whereas it can remain unchanged for a local preview.

**Comment by bernhold** [comment]
More from Clara
> Serving them "locally" to the site (i.e. from Parallactic's server) would add a lot of overhead to our system -- we'd have to copy the files from github to the server that runs the site (thus making rebuilds take longer - probably a lot longer - and possibly increasing hosting costs depending on how much storage is needed).

**Comment by bartlettroscoe** [comment]
@bernhold, it would be good if I could talk with Parallactic one-on-one about the technical issues of git-lfs.

**Comment by bartlettroscoe** [comment]
> is about being able to easily author markdown content that refs a locally known image file (e.g. `![](../images/foo.png)` without having to a) specify a GitHub raw URL for it and b) having to already have it uploaded to GitHub so that you can c) preview the site locally even when some of the (proposed) images are known only locally. Is that right?

@markcmiller86, correct, local relative references are the key here.

**Comment by markcmiller86** [comment]
> @markcmiller86, correct, local relative references are the key here.

Ok, sure. I believe that issue is manageable with appropriate `config.yml` files for *local* and *gh-pages* generation.

**Comment by bernhold** [comment]
@markcmiller86 remember, this is not a Jekyll site.  There is no config.yml.  And there is, at present, no "local generation" per se.  I think what @bartlettroscoe is shooting for here is the convenience of being having things appear (reasonably) sensibly in authoring tools, including the GitHub web UI.  Which I agree is desirable.

**Comment by markcmiller86** [comment]
> @markcmiller86 remember, this is not a Jekyll site. There is no config.yml. And there is, at present, no "local generation" per se. I think what @bartlettroscoe is shooting for here is the convenience of being having things appear (reasonably) sensibly in authoring tools, including the GitHub web UI. Which I agree is desirable.

Ok, yeah. I remember that. But, also remember, many candidate authors may draft `.md` files and browse them locally with any md-capable browser or maybe draft them directly on GitHub and in those circumstances are more likely to use *normal* relative image referencing. My impression is that @bartlettroscoe is asking that that at least be possible even if it means that more logic on the site generation (backend) needs to exist to unravel those to their correct (LSF raw) URLS and that is a slightly different issue from using LSF for image content itself. I kinda agree.

All that said, another way to go is to NOT complicate things using LFS for images. We might be fine in the short term or even in the medium term. If we get *really* popular and have a lot of bandwidth due to visiters, we would want to switch to LSF'd content.

**Comment by bartlettroscoe** [comment]
>  My impression is that @bartlettroscoe is asking that that at least be possible even if it means that more logic on the site generation (backend) needs to exist to unravel those to their correct (LSF raw) URLS and that is a slightly different issue from using LSF for image content itself. I kinda agree.

@markcmiller86, yes!  Exactly!

**Comment by bartlettroscoe** [comment]
> All that said, another way to go is to NOT complicate things using LFS for images. We might be fine in the short term or even in the medium term. If we get really popular and have a lot of bandwidth due to visiters, we would want to switch to LSF'd content.

@markcmiller86, I am find avoiding LSF for now.  But if we change our minds later and decide to use LFS, then we will need to rewrite the history on all the branches to switch to LSF for those file.  Should be fine for a very simple git repo like bssw.io but it will break anyone's branches against the bssw.io repo that we can't touch in the rewrite of the history.

**Comment by bartlettroscoe** [comment]
It would be best if I could just talk with Parallactic directly about the technical issues involved.  Would likely save a lot of time speculation.

**Comment by bernhold** [comment]
@bartlettroscoe I can setup a meeting with Parallactic.  But from continuing the conversation with Clara further, here is what could be implemented pretty quickly...

1) Images should be moved to a single directory in the bssw.io repo (i.e., images) rather than being scattered through the various article directories (I don't think we ever imagined anything else)
 2) The source can use relative URLs, like ../../images/myhero.png and the front-end will translate them to GH raw URLs in the generated HTML
  - Corollary: we should *not* use LFS

I think this strategy would support the natural expectations for authoring tools and the GH UI to work, even before things are merged.  While minimizing the changes needed to the front-end.

**Comment by bartlettroscoe** [comment]
@bernhold,

> Images should be moved to a single directory in the bssw.io repo (i.e., images) rather than being scattered through the various article directories

Fine by me if that is what people want.

> The source can use relative URLs, like ../../images/myhero.png and the front-end will translate them to GH raw URLs in the generated HTML

Why can't they get the images from the local repo?  Why do they have to go out to GH?  Why is that a constraint?  Can't they serve images in the same server where the generated HTML files are stored?

> Corollary: we should not use LFS

Why, because of the demand to pull down image files off GH?

>  I can setup a meeting with Parallactic.

I am willing to meet with them but if we don't want to ask the above simple questions, then let's just drop this and not use git-lfs.

**Comment by bernhold** [comment]
@bartlettroscoe I've asked those questions already and haven't necessarily gotten answers.  Parallactic tends to focus on solving problems over revisiting past design decisions.

So, as I said, I think the simplest path forward is to not use LFS and have Parallactic map relative URLs in images references.

**Comment by markcmiller86** [comment]
:+1: for foregoing LFS

**Comment by bartlettroscoe** [comment]
Okay, I updated the "Tasks" list [above](https://github.com/betterscientificsoftware/bssw.io/issues/703#issue-806671486) to say that we will **not** use git-lfs and we will put all of the images under `bssw.io/images/`.  Any objections to that?  Any feedback on the remaining tasks listed above?  If not, then the next task is:

* Scope out the list of images and references that would need to be updated for the move of images from the independent 'images' repo to the main 'bssw.io' repo.

**Comment by JeanShuler** [comment]
Thanks!!
Jean

**Comment by bernhold** [comment]
Okay, we've had a lot of back and forth.  I'm going to make a concrete proposal for a practical way to proceed.  It is not as general as some might like, but I think it can be implemented easily and fairly quickly.

1. We designate a single directory for all images associated with bssw.io content.  I propose ```bssw.io/images```
    - EB docs images would *not* go here
2. We use relative URLs to refer to all images
3. Parallactic modifies the front-end code to recognize references to the images directory and rewrite them to the corresponding GitHub repository URLs
    - This allows us to continue to use gh.com as the source for our images, as we have been doing since the inception of the site (it would simply by within the bssw.io repository now rather than a separate repo).
4. We do *not* use git-lfs because then the actual files would not be served up from the GH repo URLs.

@prwolfe @bartlettroscoe as the other working group members, please let me know what you think about this proposal.

**Comment by prwolfe** [comment]
@bernhold - I expect this will work. I was concerned about name collisions so I looked at the existing repo. It is already a single directory and this will eliminate that issue and make the work for parallactic straightforward.

**Comment by bartlettroscoe** [comment]
>  I'm going to make a concrete proposal for a practical way to proceed

@davidbernholdt, yes, your summary [above](https://github.com/betterscientificsoftware/bssw.io/issues/703#issuecomment-790846968) is what we decided and what I previously documented in the completed "tasks" list [above](https://github.com/betterscientificsoftware/bssw.io/issues/703#issue-806671486).  The remaining tasks are listed there.

The item:

> We use relative URLs to refer to all images

is an unambiguous requirement in order for a single PR to have all of the files (including) images to be part of a new or modified contribution.  That was about the whole motivation for this transition in the first place.

The only one of the remaining "task" out of our control is:

> Parallactic modifies the front-end code to recognize references to the images directory and rewrite them to the corresponding GitHub repository URLs

How can we make sure they have that in place before we execute this transition?  I guess that can test this on preview.bssw.io against our PR that makes this transition as listed in the tasks above.

At this point I don't think there is anything stopping us from making that transition.

Question: Do we want to save the git history from the separate images repo or do we not care when injecting the image files into `bssw.io/images/`?  We could save history and it is not that hard to do.  However, if you want to save space in the `.git/` directory, you don't want to bother saving history for binary files.  Also, not all of the images files in that repo are likely being referenced by `*.md` files on the 'master' branch.  Also, we should not delete the images/ repo but make it read-only for a time in case we care about history.   So to cut down on space and avoid unused files, we should copy in all of the referenced image files and create one commit on `bssw.io`.  Agreed?

**Comment by bernhold** [comment]
@bartlettroscoe yes, we will definitely need to wait for PC to implement the front-end support.

I don't think there is huge value in copying over the history of the images.  I would be inclined to keep it simple.

You're right that the repo probably includes unused images.  It makes sense to me to copy over only those we actually need.  I'm  more concerned about clutter than space per se, but they both pull in the same direction. (I'd like a more systematic naming scheme, but that's something we can do separately *if* people consider it worth the time and effort. I'm not entirely sure *I* do.)

**Comment by bartlettroscoe** [comment]
> I'd like a more systematic naming scheme, but that's something we can do separately if people consider it worth the time and effort. I'm not entirely sure I do

@bernhold, the good news is that changing the name of a file (even a binary file) in git has only a very small O(1) storage overhead.  Only the changes of the link in the `*.md` would result in a new blob file for the change for that `*.md` file.  So name changes after after the initial transition no problem at all.

**Comment by bernhold** [comment]
@rinkug I think our working group is ready to report out to the full EB at the next operational meeting.

**Comment by bartlettroscoe** [comment]
Related to my epic SEPW-211

**Comment by bernhold** [comment]
Closing this in favor of #738
