### ISSUE TITLE
Add subcategory "Peer Code Review" to bssw.io

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#777]
CC: @betterscientificsoftware/bssw-editorial-board 

## Description

This Issue is to suggest/request adding the subcategory "Peer Review" under the major category  "Better Reliability" on the [bssw.io] site.

The current [bssw.io] site has several categories and subcategories.  One major subcategory that is missing is for "Peer Review".  As described in Chapter 20 "The Software-Quality Landscape" in  [Code Complete 2nd Edition], the two major tools for software quality assurance are reviews and testing.  While there are two subcategories for "testing" under the "Better Reliability" category, the work "review" does not appear in that category or any other subcategory.

Note that there are already several articles published on the bssw.io site that fall under this "Peer Review" subcategory (which can be found under the Google searches `site:bssw.io "Peer Review"` and `cite:bssw.io "Code Review"`) to initially populate this subcategory.

[bssw.io]: https://bssw.io
[Code Complete 2nd Edition]: https://bssw.io/items/code-complete-a-practical-handbook-of-software-construction

## Tasks:

* [ ] Add support for the subtopic "Peer code review" under "Better Reliability" on bssw.io (@rinkug)
* [ ] Add the subtopic "Peer code review" to the current bssw.io articles identified below (@bartlettroscoe)
* [ ] Update EB docs to define the "Peer code review" subtopic (@bartlettroscoe)

**Comment by bartlettroscoe** [comment]
Does this need to be done by the web contractor or can we add this ourselves?

Related to my epic SEPW-211

**Comment by markcmiller86** [comment]
> Related to my epic SEPW-211

Is there by chance an actual link you can include to `SEPW-211`?

**Comment by bartlettroscoe** [comment]
> Is there by chance an actual link you can include to SEPW-211?

@markcmiller86, this is just a way to link back to my internal SNL epics for internal SNL reporting.

**Comment by bernhold** [comment]
Trying to move the conversation from https://github.com/betterscientificsoftware/bssw.io/issues/409#issuecomment-928184991 to this issue.  @rinkug and @bartlettroscoe were part of that conversation.

Rinku, I am not sure I agree that there should be some minimum number of articles before we make a new topic.  I don't know what the current statistics are, but I feel sure that there are existing topics where we don't have as many as 6-7, so even if there is a minimum threshold, I strongly suspect that 6-7 is unreasonably high.

There's also the practical matter of if we wait too long to create a topic, we're going to lose track of the already published articles that *should* be in it. (Yes, we can track that in tickets like this, but it requires people remember to do it.)

To me it is important to think about topics as a tool to help people find content they're interested in.  In which case having a topic rather than wedging it under some other not-quite-right topic seems like the right approach.

**Comment by bartlettroscoe** [comment]
As I said [above](https://github.com/betterscientificsoftware/bssw.io/issues/777#issue-846856575), you can already find several articles that would go in a "Peer Review" category already on the bssw.io site including:

* https://bssw.io/items/contemporary-peer-code-review-in-scientific-software-development-escience-2018-tutorial
* https://bssw.io/items/what-constitutes-constructive-code-critique
* https://bssw.io/items/a-community-of-practice-around-peer-review-for-long-term-research-software-sustainability
* https://bssw.io/items/pull-request-size-matters
* https://bssw.io/items/accepting-high-quality-software-contributions-as-scientific-publications

That is 5 articles.  Note that [issue tracking](https://preview.bssw.io/items?topic=issue-tracking) only has 5 articles.

**Comment by bernhold** [comment]
Great!  Thanks for taking the time to look them up.

As I understand it, we actually should have complete control over topics.  They're defined in the Site directory.  I need a little time to dig in and understand the format.  More to come on that.

I think the last real question in my mind is the precise name of the new topic.  We've been saying "peer review" here, but I'd like to suggest "peer code review".  I think it is useful to get the words "code review" in there because my sense is that's the most common label for this practice.

**Comment by bartlettroscoe** [comment]
> I think the last real question in my mind is the precise name of the new topic. We've been saying "peer review" here, but I'd like to suggest "peer code review". I think it is useful to get the words "code review" in there because my sense is that's the most common label for this practice.

@bernhold, okay, I see the exact term "peer code review" used in the three articles:

* https://bssw.io/events/contemporary-peer-code-review-in-scientific-software-development-escience-2018-tutorial
* https://bssw.io/blog_posts/a-community-of-practice-around-peer-review-for-long-term-research-software-sustainability
* https://bssw.io/items/what-constitutes-constructive-code-critique

so that seems like a term already in use.

But it is also important to review requirements, designs, tests, and documentation as well, not just code.  In the book "Code Complete: 2nd Edition" McConnell holds up the two main pillars of software quality engineering as automated testing and technical reviews (of everything).  So the term "technical review" is likely more accurate for this category to catch all of this.  But I see the value of having "peer" and "code" in the name.  (And we can just expand the category to mean also reviewing requirements, designs, tests, and documentation as well.)

But any subcategory with "review" in the name under "Better Reliability" is okay with me.

**Comment by rinkug** [comment]
@bartlettroscoe : volunteered to do this.

**Comment by bartlettroscoe** [comment]
With the merge of PRs #1379 and #1382, this is complete
